name: taste_adda
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  google_sign_in: ^6.3.0
  dio: ^5.8.0+1
  provider: ^6.1.5
  go_router: ^15.1.2
  liquid_pull_to_refresh: ^3.0.1



dev_dependencies:
  icons_launcher: ^3.0.1
  rename_app: ^1.6.3
  change_app_package_name: ^1.5.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6

icons_launcher:
  image_path: "assets/images/ic_launcher.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter:
  uses-material-design: true
  

  assets:
   
   
    - assets/images/google_icon.png
    - assets/images/facebook_icon.png
    - assets/images/recip.png
    - assets/images/ic_launcher.png
    - assets/images/splash_image.png

    

